### ISSUE TITLE
DeltaKinematicsCalibrationTool.exe is a hexdump, not a binary

### ISSUE THREAD

**Issue by Patola** [RollieRowland/Delta-Bed-Calibration-Tool#4]
When you open DeltaKinematicsCalibrationTool.exe all you has is something like this:

4d5a 9000 0300 0000 0400 0000 ffff 0000
b800 0000 0000 0000 4000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 8000 0000
0e1f ba0e 00b4 09cd 21b8 014c cd21 5468
6973 2070 726f 6772 616d 2063 616e 6e6f
7420 6265 2072 756e 2069 6e20 444f 5320
6d6f 6465 2e0d 0d0a 2400 0000 0000 0000
5045 0000 4c01 0300 29af b955 0000 0000
0000 0000 e000 2200 0b01 3000 0068 0000

In TEXT format. It is not binary at all. So, it is not compiled. If you transform the hex to binary it seems to generate a valid .exe:

`$ xxd -r -p DeltaKinematicsCalibrationTool.exe test.exe`
`$ file ./test.exe`
`test.exe: PE32 executable (GUI) Intel 80386 Mono/.Net assembly, for MS Windows`
`$`

**Comment by Hertzz58** [comment]
Yes, this was the debug version of the program, not a release. I went ahead and actually removed these files as they were only a C# version of the html file - an intermediate state between the manual and automatic calibration. If the newer version of the program is what you were looking for then here it is - https://github.com/RollieRowland/OpenDACT
